package escuelaing.edu.co.demo;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.datatype.jsr310.JavaTimeModule;
import escuelaing.edu.co.domain.model.BenchmarkResult;
import escuelaing.edu.co.domain.model.DegradationReport;
import escuelaing.edu.co.domain.model.LoadProfile;
import escuelaing.edu.co.domain.model.validation.ValidationReport;
import escuelaing.edu.co.infrastructure.analysis.BaselineManager;
import escuelaing.edu.co.infrastructure.analysis.DegradationDetector;
import escuelaing.edu.co.infrastructure.benchmark.BenchmarkRunner;
import escuelaing.edu.co.infrastructure.capture.LoadProfileMerger;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

import java.io.File;
import java.io.PrintWriter;
import java.util.List;

/**
 * Entry point for the CPT-SQL benchmark engine (phases 3 and 4).
 *
 * <p>Reads the load profile generated by {@link EcommerceSimulator} (phase 2),
 * runs the benchmark against the mirror database, and detects degradations
 * against the committed {@code baseline.json}.</p>
 *
 * <h3>Exit codes</h3>
 * <ul>
 *   <li>{@code 0} — no blocking degradations (BASELINE_EXCEEDED warnings may be present).</li>
 *   <li>{@code 1} — P95_EXCEEDED, SLO_PROXIMITY, or PLAN_CHANGED detected.</li>
 * </ul>
 *
 * <h3>Key parameters</h3>
 * <pre>
 * --loadtest.profile.path     path to the production load profile (stats + SQL)
 * --loadtest.profile.sqlPath  path to the PR SQL profile; if different from profile.path,
 *                             capturedSql fields are merged before the benchmark runs
 * </pre>
 */
@SpringBootApplication(scanBasePackages = {
        "escuelaing.edu.co.infrastructure",
        "escuelaing.edu.co.demo"
})
public class BenchmarkMain {

    public static void main(String[] args) {
        System.exit(SpringApplication.exit(SpringApplication.run(BenchmarkMain.class, args)));
    }

    @Bean
    CommandLineRunner run(BenchmarkRunner benchmarkRunner,
                          DegradationDetector detector,
                          BaselineManager baselineManager,
                          @Value("${loadtest.profile.path:load-profile.json}") String profilePath,
                          @Value("${loadtest.profile.sqlPath:}") String sqlPath) {
        return args -> {
            ObjectMapper mapper = new ObjectMapper().registerModule(new JavaTimeModule());

            // --- Load production profile (statistics) ---
            File profileFile = new File(profilePath);
            if (!profileFile.exists()) {
                System.err.println("[BenchmarkMain] Profile not found: " + profilePath);
                System.err.println("  Run first: ./gradlew :sql-testing-demo:runSimulator");
                System.exit(1);
            }
            LoadProfile profile = mapper.readValue(profileFile, LoadProfile.class);
            System.out.println("[BenchmarkMain] Profile loaded: "
                    + profile.getTotalSamples() + " samples, "
                    + profile.getQueries().size() + " queries.");

            // --- Merge PR SQL into production profile (if a separate SQL profile was provided) ---
            // The production profile stats (p95Ms, meanMs, callsPerMinute, etc.) are preserved.
            // Only capturedSql is updated per queryId from the PR profile.
            boolean hasSqlProfile = sqlPath != null && !sqlPath.isBlank()
                    && !sqlPath.equals(profilePath);
            if (hasSqlProfile) {
                File sqlFile = new File(sqlPath);
                if (sqlFile.exists()) {
                    LoadProfile prProfile = mapper.readValue(sqlFile, LoadProfile.class);
                    int merged = LoadProfileMerger.merge(profile, prProfile);
                    System.out.println("[BenchmarkMain] PR SQL merged for " + merged + " queries.");
                } else {
                    System.err.println("[BenchmarkMain] PR SQL profile not found: " + sqlPath
                            + " — using capturedSql from production profile.");
                }
            }

            // --- Synthesis fidelity validation (SynQB) ---
            try {
                ValidationReport validationReport = benchmarkRunner.performValidation(profile);
                benchmarkRunner.persistValidationReport(validationReport);
                System.out.println("[BenchmarkMain] VALIDATION_REPORT.json generated — "
                        + validationReport.getValidationStatus());
            } catch (Exception e) {
                System.err.println("[BenchmarkMain] Fidelity validation skipped: " + e.getMessage());
            }

            // --- Phase 3 + Phase 4: benchmark and persistence ---
            String commitSha = System.getenv("GITHUB_SHA");
            BenchmarkResult result = benchmarkRunner.run(profile, commitSha);

            // --- Degradation detection vs baseline.json ---
            DegradationReport report = detector.detect(result);

            // --- Results report ---
            System.out.println("\n=== BENCHMARK RESULT ===");
            System.out.println("Verdict  : " + result.getOverallVerdict());
            System.out.println("Profile  : " + result.getTestProfileName());
            System.out.println("Samples  : " + result.getTotalOperations());
            result.getQueries().forEach((qid, qr) -> {
                String risk = "";
                if (qr.getSlaRiskPct() >= 90)      risk = "  !! CRITICAL: " + String.format("%.0f%%", qr.getSlaRiskPct()) + " of SLA";
                else if (qr.getSlaRiskPct() >= 70)  risk = "  !! WARNING: "  + String.format("%.0f%%", qr.getSlaRiskPct()) + " of SLA";
                System.out.printf("  %-35s p95=%5.0f ms  sla=%.1f%%  verdict=%s%s%n",
                        qid, qr.getP95Ms(), qr.getSlaComplianceRate(), qr.getVerdict(), risk);
            });

            // --- Classify degradations: blocking (exit 1) vs warnings (exit 0) ---
            List<DegradationReport.Degradation> blocking = report.getDegradations().stream()
                    .filter(r -> r.getType() == DegradationReport.DegradationType.P95_EXCEEDED
                              || r.getType() == DegradationReport.DegradationType.PLAN_CHANGED
                              || r.getType() == DegradationReport.DegradationType.SLO_PROXIMITY)
                    .collect(java.util.stream.Collectors.toList());

            List<DegradationReport.Degradation> warnings = report.getDegradations().stream()
                    .filter(r -> r.getType() == DegradationReport.DegradationType.BASELINE_EXCEEDED)
                    .collect(java.util.stream.Collectors.toList());

            if (!warnings.isEmpty()) {
                System.out.println("\n=== DEGRADATION WARNINGS (non-blocking) ===");
                warnings.forEach(r -> System.out.println("  " + r.getDescription()));

                boolean shouldPublish = blocking.isEmpty() && warnings.stream().anyMatch(r -> {
                    BenchmarkResult.QueryResult qr = result.getQueries().get(r.getQueryId());
                    return qr != null && qr.getSlaRiskPct() >= 50.0;
                });
                if (shouldPublish) {
                    try (PrintWriter pw = new PrintWriter("benchmark-warnings.txt")) {
                        pw.println("🟡 **CPT-SQL — Degradation warning**\n");
                        warnings.forEach(r -> {
                            BenchmarkResult.QueryResult qr = result.getQueries().get(r.getQueryId());
                            String slaLine = (qr != null && qr.getSlaRiskPct() < 100)
                                    ? String.format("SLA still met (%.0f%% of limit) — merge is allowed.", qr.getSlaRiskPct())
                                    : "SLA still met — merge is allowed.";
                            pw.println(r.getDescription());
                            pw.println(slaLine);
                            pw.println();
                        });
                    } catch (Exception e) {
                        System.err.println("[BenchmarkMain] Could not write benchmark-warnings.txt: " + e.getMessage());
                    }
                }
            }

            if (!blocking.isEmpty()) {
                System.err.println("\n=== CRITICAL DEGRADATIONS DETECTED ===");
                blocking.forEach(r ->
                    System.err.println("  [FAIL] [" + r.getType() + "] " + r.getDescription()));
                System.exit(1);
            }

            // --- Update baseline on PASS ---
            // baseline.json is updated by update-baseline.yml (post-merge push),
            // not during PR runs — keeping the baseline on approved code only.
            if (result.getOverallVerdict() == BenchmarkResult.Verdict.PASS) {
                baselineManager.save(result);
                System.out.println("\n[BenchmarkMain] baseline.json updated.");
            }

            System.out.println("[BenchmarkMain] Pipeline OK."
                    + (warnings.isEmpty() ? "" : " (with degradation warnings)"));
        };
    }
}
