name: Baseline — Update post-merge

on:
  push:
    branches: [main, develop, qa]
    paths-ignore:
      - 'baseline.json'
      - 'load-profile.json'
      - '**/*.md'
      - 'NOTICE'
      - 'LICENSE'
      - '.gitignore'
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  call-cpt-update-baseline:
    uses: Alizeci/CPT-SQL/.github/workflows/update-baseline.yml@main
    with:
      schema-script: src/main/resources/schema-ecommerce.sql
      jar-path: build/libs/sql-testing-demo.jar
      rows-per-table: 400000
      test-profile: light
